### ISSUE TITLE
Can your tta wrapper use with weight file save by save_weight only with keras callback function ?

### ISSUE THREAD

**Issue by xDzai94** [qubvel/tta_wrapper#2]

**Comment by qubvel** [comment]
Hi @xDzai94 
Not sure I understand your question, could you explain it more detailed?

**Comment by xDzai94** [comment]
Hi, I am using https://github.com/matterport/Mask_RCNN this repo to implement something, but somehow their code only can save with model.save_weight instead of model.save_model where the .h5 file would only consist of weight info without model architecture and therefore I tried to run with your example description but it comes out error in the input_shape so I wonder is there any alternative way to use your code ?

**Comment by xDzai94** [comment]
The error is as below

AttributeError                            Traceback (most recent call last)
<ipython-input-24-ccc4051a3b44> in <module>
----> 1 tta_model = tta_classification(model, h_flip=True, merge='mean')

~\Anaconda3\envs\tensorflow\lib\site-packages\tta_wrapper\wrappers.py in tta_classification(model, h_flip, v_flip, h_shift, v_shift, rotation, contrast, add, mul, merge)
     89                        )
     90 
---> 91     input_shape = (1, *model.input.shape.as_list()[1:])
     92 
     93     inp = Input(batch_shape=input_shape)

AttributeError: 'MaskRCNN' object has no attribute 'input'

Appreciate your reply.

**Comment by qubvel** [comment]
This wrapper is not suitable for such kind of model. Model should be classification or segmentation (1 input - 1 output).
