### ISSUE TITLE
AttributeError. Asking for help. 

### ISSUE THREAD

**Issue by 8188** [qubvel/tta_wrapper#6]
AttributeError                            Traceback (most recent call last)
<ipython-input-34-71cdfe121528> in <module>()
      2 model = tta_segmentation(model, 
      3                          h_flip=True,
----> 4                          h_shift=(-5, 5),
      5                          #merge='mean'
      6                         )

C:\Anaconda3\lib\site-packages\tta_wrapper\wrappers.py in tta_segmentation(model, h_flip, v_flip, h_shift, v_shift, rotation, contrast, add, mul, merge)
     52                        )
     53 
---> 54     input_shape = (1, *model.input.shape.as_list()[1:])
     55 
     56     inp = Input(batch_shape=input_shape)

C:\Anaconda3\lib\site-packages\keras\engine\base_layer.py in input(self)
    782         if len(self._inbound_nodes) > 1:
    783             raise AttributeError('Layer ' + self.name +
--> 784                                  ' has multiple inbound nodes, '
    785                                  'hence the notion of "layer input" '
    786                                  'is ill-defined. '

AttributeError: Layer sequential_1 has multiple inbound nodes, hence the notion of "layer input" is ill-defined. Use `get_input_at(node_index)` instead.

**Comment by qubvel** [comment]
Hi
This error fixed in latest version (install from source). It is appers when you have more than one model for the same graph, and the workaround is to provide input_shape of the model to wrapper
