### ISSUE TITLE
Any plan to upgrade it for TF Keras?

### ISSUE THREAD

**Issue by urvishp80** [qubvel/tta_wrapper#9]
This is a nice package to have. So are there any plans to upgrade it for TF Keras? I would like to contribute if you are planning to do so. Let me know your thoughts.

**Comment by innat** [comment]
I've made the necessary changes to `tensorflow 2.x`. Here are the modified [code](https://www.kaggle.com/ipythonx/keras-tta-wrapper) and usages of it in the [inference](https://www.kaggle.com/ipythonx/tf-keras-melanoma-classification-starter-tabnet#Test-Gens-with-TTA-and-Submission) section.

**Comment by urvishp80** [comment]
Thanks. I will take a look at that.
